# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "hicqc"
description: A (very) simple script to QC Hi-C data
keywords:
  - genomics
  - bam
  - hic
  - qc
tools:
  - "hicqc":
      description: "A (very) simple script to QC Hi-C data"
      homepage: "https://github.com/phasegenomics/hic_qc"
      documentation: "https://github.com/phasegenomics/hic_qc"
      tool_dev_url: "https://github.com/gallvp/hic_qc"
      licence: ["GNU GPL v3"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - bam:
        type: file
        description: BAM file
        pattern: "*.{bam}"

        ontologies: []
output:
  pdf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.pdf":
          type: file
          description: PDF report
          pattern: "*.{pdf}"
          ontologies: []
  html:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.html":
          type: file
          description: HTML report
          pattern: "*.{html}"

          ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"

        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@GallVp"
maintainers:
  - "@GallVp"
