# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "helitronscanner_draw"
description: HelitronScanner for Helitron transposons in genomes
keywords:
  - genomics
  - helitron
  - scanner
tools:
  - "helitronscanner":
      description: "HelitronScanner uncovers a large overlooked cache of Helitron transposons
        in many genomes"
      homepage: "https://sourceforge.net/projects/helitronscanner"
      documentation: "https://sourceforge.net/projects/helitronscanner"
      tool_dev_url: "https://sourceforge.net/projects/helitronscanner"
      doi: "10.1073/pnas.1410068111"
      licence: ["GPL v3-or-later"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - fasta:
        type: file
        description: Genome data to scan for Helitrons
        pattern: "*.{fa,fsa,fasta}"
  - - head:
        type: file
        description: Output of the HelitronScanner head command
        pattern: "*.head"
  - - tail:
        type: file
        description: Output of the HelitronScanner tail command
        pattern: "*.tail"
  - - rc:
        type: value
        description: |
          Whether this is being run on the reverse complement output files
output:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - draw:
        type: files
        description: Output of the HelitronScanner draw command
        pattern: "*.draw.*"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@GallVp"
  - "@jguhlin"
maintainers:
  - "@GallVp"
