# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "fasta_bedtools_makewindows_nuc"
description: Take a fasta and compute GC content
keywords:
  - fasta
  - bed
  - GC
components:
  - samtools/faidx
  - bedtools/makewindows
  - bedtools/nuc
input:
  - ch_fasta:
      type: file
      pattern: "*.fasta"
      description: Input fasta file
output:
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
  - nuc:
      type: file
      description: BED file with GC and other stats
      pattern: "*.bed"
authors:
  - "@GallVp"
maintainers:
  - "@GallVp"
