---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "annosine"
channels:
  - conda-forge
  - bioconda

dependencies:
  - "bioconda::annosine2=2.0.7"
