---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "custom_relabelfasta"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython==1.75
  - python==3.8.13
