# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "agat_spcomplementannotations"
description: |
  The script allows to complement a reference annotation with other annotations.
keywords:
  - genomics
  - gff
  - merge
  - combine
tools:
  - "agat":
      description: "Another Gff Analysis Toolkit (AGAT). Suite of tools to handle gene
        annotations in any GTF/GFF format."
      homepage: "https://agat.readthedocs.io/en/latest/"
      documentation: "https://agat.readthedocs.io/en/latest/tools/agat_sp_merge_annotations.html"
      tool_dev_url: "https://github.com/NBISweden/AGAT"
      doi: "10.5281/zenodo.3552717"
      licence: ["GPL v3"]
      identifier: biotools:AGAT
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - ref_gff:
        type: file
        description: Reference Gff
        pattern: "*.{gff,gff3}"
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - add_gffs:
        type: list
        description: A list of Gff files to be added to teh reference annotation
        pattern: "*.{gff,gff3}"
  - - config:
        type: file
        description: |
          Input agat config file. By default AGAT takes as input agat_config.yaml file from the working directory if any,
          otherwise it takes the original agat_config.yaml shipped with AGAT. To get the agat_config.yaml
          locally type: "agat config --expose". The --config option gives you the possibility to use your
          own AGAT config file (located elsewhere or named differently).
        pattern: "*.yaml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
output:
  - gff:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.gff":
          type: file
          description: Output GFF file.
          pattern: "*.gff"
          ontologies: []
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
          ontologies:
            - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@GallVp"
maintainers:
  - "@GallVp"
