# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "fasta_helitronscanner_scan_draw"
description: Find helitrons suing Helitronscanner scan, pairends and draw subcommands
keywords:
  - helitron
  - scan
  - draw
  - pairends
  - repeat
  - genomics
  - fasta
components:
  - helitronscanner/scan
  - helitronscanner/draw
input:
  - ch_fata:
      type: file
      description: |
        The input channel containing the FASTA file
        Structure: [ val(meta), path(fasta) ]
      pattern: "*.fasta"
output:
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@GallVp"
maintainers:
  - "@GallVp"
  - "@jguhlin"
