# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "helitronscanner_scantail"
description: HelitronScanner for Helitron transposons in genomes
keywords:
  - genomics
  - helitron
  - scanner
tools:
  - "helitronscanner":
      description: "HelitronScanner uncovers a large overlooked cache of Helitron transposons
        in many genomes"
      homepage: "https://sourceforge.net/projects/helitronscanner"
      documentation: "https://sourceforge.net/projects/helitronscanner"
      tool_dev_url: "https://sourceforge.net/projects/helitronscanner"
      doi: "10.1073/pnas.1410068111"
      licence: ["GPL v3-or-later"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - fasta:
        type: file
        description: Genome data to scan for Helitrons
        pattern: "*.{fa,fsa,fasta}"
  - - lcv_filepath:
        type: file
        description: LCV file path. If not provided by setting it to [], the LCV file
          packaged with the module will be used
        pattern: "*.lcvs"
  - - buffer_size:
        type: integer
        description: Genome slice size (use negative or zero for non-buffer, i.e. treat
          every whole chromosome)
  - - rc:
        type: value
        description: |
          Whether this is being run on the reverse complement output files
output:
  - head:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*.head":
          type: file
          description: Scanned Helitrons
          pattern: "*.head"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@GallVp"
  - "@jguhlin"
maintainers:
  - "@GallVp"
