# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "hictk_zoomify"
description: Zoomify hic files to add more resolutions
keywords:
  - genomics
  - hic
  - 4dn
  - pairs
tools:
  - "hictk":
      description: "Blazing fast toolkit to work with .hic and .cool files"
      homepage: "https://github.com/paulsengroup/hictk#readme"
      documentation: "https://github.com/paulsengroup/hictk#readme"
      tool_dev_url: "https://github.com/paulsengroup/hictk"
      doi: "10.1093/bioinformatics/btae408"
      licence: ["MIT"]
      identifier: biotools:hictk
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - hic:
        type: file
        description: Input hic
output:
  hic:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.hic":
          type: file
          description: Output hic file
          ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"

        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@GallVp"
maintainers:
  - "@GallVp"
