# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "yahs_juicerpre"
description: Generate files compatible with Juicebox toolset
keywords:
  - genomics
  - hic
  - bam
  - juicer
tools:
  - "yahs":
      description: "YaHS, yet another Hi-C scaffolding tool."
      homepage: "https://github.com/c-zhou/yahs"
      documentation: "https://github.com/c-zhou/yahs"
      tool_dev_url: "https://github.com/c-zhou/yahs"
      doi: "10.1093/bioinformatics/btac808"
      licence: ["MIT"]
      identifier: biotools:yahs

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`

    - bam_or_bin:
        type: file
        description: BAM or BIN file
        pattern: "*.{bam,bin}"
        ontologies:
          - edam: "http://edamontology.org/format_2572" # BAM
          - edam: "http://edamontology.org/format_2573" # CRAM
          - edam: "http://edamontology.org/format_3462" # SAM
  - - agp:
        type: file
        description: AGP file
        pattern: "*.agp"

        ontologies: []
  - - fai:
        type: file
        description: FAI file
        pattern: "*.fai"

        ontologies: []
output:
  - txt:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.txt":
          type: file
          description: Links TSV file
          pattern: "*.txt"
          ontologies: []
  - assembly:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.assembly":
          type: file
          description: Assembly file
          pattern: "*.assembly"
          ontologies: []
  - assembly_agp:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.assembly.agp":
          type: file
          description: Assembly AGP file
          pattern: "*.assembly.agp"
          ontologies: []
  - liftover_agp:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.liftover.agp":
          type: file
          description: Liftover AGP file
          pattern: "*.liftover.agp"

          ontologies: []
  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

          ontologies:
            - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@GallVp"
maintainers:
  - "@GallVp"
