---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "tesorter"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::tesorter=1.4.6"
