---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "tesorter"
description: An accurate and fast method to classify LTR-retrotransposons in plant genomes
keywords:
  - genomics
  - classify
  - LTR
  - retrotransposons
  - plant
tools:
  - "tesorter":
      description: "Lineage-level classification of transposable elements using conserved protein domains."
      homepage: "https://github.com/zhangrengang/TEsorter"
      documentation: "https://github.com/zhangrengang/TEsorter"
      tool_dev_url: "https://github.com/zhangrengang/TEsorter"
      doi: "10.1093/hr/uhac017"
      licence: ["GPL v3"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1' ]`
  - fasta:
      type: file
      description: Input sequence
      pattern: "*.{fa,fasta,fsa,faa}"
  - db_hmm:
      type: file
      optional: true
      description: The database HMM file used
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1' ]`
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - domtbl:
      type: file
      description: HMMScan raw output
      pattern: "*.domtbl"
  - dom_faa:
      type: file
      description: Protein sequences of domain, which can be used for phylogenetic analysis
      pattern: "*.dom.faa"
  - dom_tsv:
      type: file
      description: Inner domains of TEs/LTR-RTs, which might be used to filter domains based on their scores and coverages
      pattern: "*.dom.tsv"
  - dom_gff3:
      type: file
      description: Domain annotations in 'gff3' format
      pattern: "*.dom.gff3"
  - cls_tsv:
      type: file
      description: TEs/LTR-RTs classifications
      pattern: "*.cls.tsv"
  - cls_lib:
      type: file
      description: Fasta library for RepeatMasker
      pattern: "*.cls.lib"
  - cls_pep:
      type: file
      description: The same sequences as '*.dom.faa', but id is changed with classifications
      pattern: "*.cls.pep"
authors:
  - "@GallVp"
maintainers:
  - "@GallVp"
