# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "bam_fasta_yahs_juicer_pre_juicer_tools_pre"
description: Takes a BAM and a FASTA to create a HiC file
keywords:
  - bam
  - fasta
  - hic
components:
  - samtools/faidx
  - juiceboxscripts/makeagpfromfasta
  - juicertools/pre
  - yahs/juicerpre
  - sort
input:
  - ch_bam:
      type: file
      description: |
        The input channel containing the BAM file
        Structure: [ val(meta), path(bam) ]
      pattern: "*.{bam}"
  - ch_fasta:
      type: file
      description: |
        The input channel containing the FASTA file
        Structure: [ val(meta2), path(fasta) ]
      pattern: "*.{fasta}"
  - val_assembly_mode:
      type: Boolean
      description: |
        Turn on/off assembly mode '-a' for YAHS_JUICERPRE
output:
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
  - hic:
      type: file
      description: |
        The output channel containing the HiC file
        Structure: [ val(meta), path(fasta) ]
      pattern: "*.{hic}"
  - assembly:
      type: file
      description: |
        The output channel containing the assembly file
        Structure: [ val(meta), path(assembly) ]
      pattern: "*.{assembly}"
  - assembly_agp:
      type: file
      description: |
        The output channel containing the assembly agp file
        Structure: [ val(meta), path(assembly) ]
      pattern: "*.{agp}"
authors:
  - "@GallVp"
maintainers:
  - "@GallVp"
