---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "syri"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::syri=1.7.0"
